-- =====================================================
-- Ling Hua Vocabulary Expansion: ~440 new words
-- Target: 500+ total words across beginner/intermediate/advanced
-- For Arabic-speaking Mandarin learners in UAE
-- =====================================================

-- =====================================================
-- BEGINNER LEVEL (~170 new words)
-- =====================================================

-- GREETINGS (beginner) — additional greetings & polite phrases
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('你好吗', 'nǐ hǎo ma', 'كيف حالك؟', 'beginner', 'greetings'),
('很好', 'hěn hǎo', 'بخير جداً', 'beginner', 'greetings'),
('不好', 'bù hǎo', 'ليس بخير', 'beginner', 'greetings'),
('晚安', 'wǎn ān', 'تصبح على خير', 'beginner', 'greetings'),
('拜拜', 'bài bài', 'مع السلامة', 'beginner', 'greetings'),
('您好', 'nín hǎo', 'مرحباً (رسمي)', 'beginner', 'greetings'),
('谢谢你', 'xiè xie nǐ', 'شكراً لك', 'beginner', 'greetings'),
('不客气', 'bú kè qì', 'عفواً / لا شكر على واجب', 'beginner', 'greetings'),
('对不起我迟到了', 'duì bu qǐ wǒ chí dào le', 'آسف على التأخير', 'beginner', 'greetings'),
('你好吗朋友', 'nǐ hǎo ma péng yǒu', 'كيف حالك يا صديقي؟', 'beginner', 'greetings'),
('好久不见', 'hǎo jiǔ bú jiàn', 'لم نلتقِ منذ فترة طويلة', 'beginner', 'greetings'),
('祝你好运', 'zhù nǐ hǎo yùn', 'حظاً سعيداً', 'beginner', 'greetings'),
('恭喜', 'gōng xǐ', 'مبروك / تهانينا', 'beginner', 'greetings'),
('生日快乐', 'shēng rì kuài lè', 'عيد ميلاد سعيد', 'beginner', 'greetings'),
('新年快乐', 'xīn nián kuài lè', 'سنة جديدة سعيدة', 'beginner', 'greetings');

-- FAMILY (beginner) — extended family & relationships
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('爷爷', 'yé ye', 'جد (من جهة الأب)', 'beginner', 'family'),
('奶奶', 'nǎi nai', 'جدة (من جهة الأب)', 'beginner', 'family'),
('外公', 'wài gōng', 'جد (من جهة الأم)', 'beginner', 'family'),
('外婆', 'wài pó', 'جدة (من جهة الأم)', 'beginner', 'family'),
('儿子', 'ér zi', 'ابن', 'beginner', 'family'),
('女儿', 'nǚ ér', 'ابنة', 'beginner', 'family'),
('丈夫', 'zhàng fu', 'زوج', 'beginner', 'family'),
('妻子', 'qī zi', 'زوجة', 'beginner', 'family'),
('叔叔', 'shū shu', 'عم', 'beginner', 'family'),
('阿姨', 'ā yí', 'خالة / عمة', 'beginner', 'family'),
('表哥', 'biǎo gē', 'ابن عم/خال أكبر', 'beginner', 'family'),
('表姐', 'biǎo jiě', 'ابنة عم/خال أكبر', 'beginner', 'family'),
('孩子', 'hái zi', 'طفل / أطفال', 'beginner', 'family'),
('宝宝', 'bǎo bao', 'رضيع', 'beginner', 'family'),
('父母', 'fù mǔ', 'والدان', 'beginner', 'family');

-- NUMBERS (beginner) — numbers beyond 10
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('零', 'líng', 'صفر', 'beginner', 'numbers'),
('百', 'bǎi', 'مئة', 'beginner', 'numbers'),
('千', 'qiān', 'ألف', 'beginner', 'numbers'),
('万', 'wàn', 'عشرة آلاف', 'beginner', 'numbers'),
('十一', 'shí yī', 'أحد عشر', 'beginner', 'numbers'),
('十二', 'shí èr', 'اثنا عشر', 'beginner', 'numbers'),
('二十', 'èr shí', 'عشرون', 'beginner', 'numbers'),
('三十', 'sān shí', 'ثلاثون', 'beginner', 'numbers'),
('五十', 'wǔ shí', 'خمسون', 'beginner', 'numbers'),
('一百', 'yì bǎi', 'مئة', 'beginner', 'numbers'),
('第一', 'dì yī', 'الأول', 'beginner', 'numbers'),
('第二', 'dì èr', 'الثاني', 'beginner', 'numbers'),
('第三', 'dì sān', 'الثالث', 'beginner', 'numbers'),
('两', 'liǎng', 'اثنان (للعد)', 'beginner', 'numbers'),
('半', 'bàn', 'نصف', 'beginner', 'numbers');

-- BASICS (beginner) — pronouns, common verbs, basic adjectives, question words
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('我', 'wǒ', 'أنا', 'beginner', 'basics'),
('你', 'nǐ', 'أنتَ / أنتِ', 'beginner', 'basics'),
('他', 'tā', 'هو', 'beginner', 'basics'),
('她', 'tā', 'هي', 'beginner', 'basics'),
('我们', 'wǒ men', 'نحن', 'beginner', 'basics'),
('你们', 'nǐ men', 'أنتم', 'beginner', 'basics'),
('他们', 'tā men', 'هم', 'beginner', 'basics'),
('这', 'zhè', 'هذا', 'beginner', 'basics'),
('那', 'nà', 'ذلك', 'beginner', 'basics'),
('什么', 'shén me', 'ماذا؟', 'beginner', 'basics'),
('谁', 'shéi', 'مَن؟', 'beginner', 'basics'),
('哪里', 'nǎ lǐ', 'أين؟', 'beginner', 'basics'),
('为什么', 'wèi shén me', 'لماذا؟', 'beginner', 'basics'),
('怎么', 'zěn me', 'كيف؟', 'beginner', 'basics'),
('多少', 'duō shǎo', 'كم؟', 'beginner', 'basics'),
('几', 'jǐ', 'كم (عدد صغير)؟', 'beginner', 'basics'),
('有', 'yǒu', 'يملك / يوجد', 'beginner', 'basics'),
('没有', 'méi yǒu', 'لا يملك / لا يوجد', 'beginner', 'basics'),
('要', 'yào', 'يريد / يحتاج', 'beginner', 'basics'),
('不要', 'bú yào', 'لا تريد / لا', 'beginner', 'basics'),
('可以', 'kě yǐ', 'يمكن / مسموح', 'beginner', 'basics'),
('不可以', 'bù kě yǐ', 'لا يمكن / غير مسموح', 'beginner', 'basics'),
('去', 'qù', 'يذهب', 'beginner', 'basics'),
('来', 'lái', 'يأتي', 'beginner', 'basics'),
('看', 'kàn', 'ينظر / يشاهد', 'beginner', 'basics'),
('说', 'shuō', 'يقول / يتكلم', 'beginner', 'basics'),
('听', 'tīng', 'يسمع / يستمع', 'beginner', 'basics'),
('读', 'dú', 'يقرأ', 'beginner', 'basics'),
('写', 'xiě', 'يكتب', 'beginner', 'basics'),
('做', 'zuò', 'يفعل / يصنع', 'beginner', 'basics'),
('会', 'huì', 'يستطيع / سوف', 'beginner', 'basics'),
('能', 'néng', 'يقدر', 'beginner', 'basics'),
('想', 'xiǎng', 'يفكر / يريد', 'beginner', 'basics'),
('知道', 'zhī dào', 'يعرف', 'beginner', 'basics'),
('不知道', 'bù zhī dào', 'لا يعرف', 'beginner', 'basics'),
('大', 'dà', 'كبير', 'beginner', 'basics'),
('小', 'xiǎo', 'صغير', 'beginner', 'basics'),
('好', 'hǎo', 'جيد', 'beginner', 'basics'),
('坏', 'huài', 'سيء', 'beginner', 'basics'),
('多', 'duō', 'كثير', 'beginner', 'basics'),
('少', 'shǎo', 'قليل', 'beginner', 'basics'),
('新', 'xīn', 'جديد', 'beginner', 'basics'),
('旧', 'jiù', 'قديم', 'beginner', 'basics'),
('长', 'cháng', 'طويل', 'beginner', 'basics'),
('短', 'duǎn', 'قصير', 'beginner', 'basics'),
('高', 'gāo', 'مرتفع / طويل القامة', 'beginner', 'basics'),
('矮', 'ǎi', 'قصير القامة', 'beginner', 'basics'),
('热', 'rè', 'حار', 'beginner', 'basics'),
('冷', 'lěng', 'بارد', 'beginner', 'basics'),
('快', 'kuài', 'سريع', 'beginner', 'basics'),
('慢', 'màn', 'بطيء', 'beginner', 'basics'),
('对', 'duì', 'صحيح', 'beginner', 'basics'),
('错', 'cuò', 'خطأ', 'beginner', 'basics'),
('男', 'nán', 'ذكر', 'beginner', 'basics'),
('女', 'nǚ', 'أنثى', 'beginner', 'basics'),
('人', 'rén', 'شخص / إنسان', 'beginner', 'basics'),
('中国', 'zhōng guó', 'الصين', 'beginner', 'basics'),
('中文', 'zhōng wén', 'اللغة الصينية', 'beginner', 'basics'),
('阿拉伯', 'ā lā bó', 'عربي', 'beginner', 'basics'),
('名字', 'míng zi', 'اسم', 'beginner', 'basics'),
('岁', 'suì', 'سنة (عمر)', 'beginner', 'basics'),
('在', 'zài', 'في / يوجد في', 'beginner', 'basics'),
('也', 'yě', 'أيضاً', 'beginner', 'basics'),
('都', 'dōu', 'كلّ / جميعاً', 'beginner', 'basics'),
('很', 'hěn', 'جداً', 'beginner', 'basics'),
('太', 'tài', 'أكثر من اللازم', 'beginner', 'basics'),
('了', 'le', 'علامة تغيّر الحال', 'beginner', 'basics'),
('的', 'de', 'أداة ملكية', 'beginner', 'basics'),
('吗', 'ma', 'أداة استفهام', 'beginner', 'basics'),
('呢', 'ne', 'وأنت؟ / ماذا عن؟', 'beginner', 'basics'),
('和', 'hé', 'و (حرف عطف)', 'beginner', 'basics'),
('还是', 'hái shì', 'أو (في السؤال)', 'beginner', 'basics'),
('但是', 'dàn shì', 'لكن', 'beginner', 'basics'),
('因为', 'yīn wèi', 'لأن', 'beginner', 'basics'),
('所以', 'suǒ yǐ', 'لذلك', 'beginner', 'basics'),
('如果', 'rú guǒ', 'إذا', 'beginner', 'basics'),
('给', 'gěi', 'يعطي / لِـ', 'beginner', 'basics'),
('跟', 'gēn', 'مع', 'beginner', 'basics'),
('从', 'cóng', 'من (مكان/زمان)', 'beginner', 'basics'),
('到', 'dào', 'إلى / يصل', 'beginner', 'basics'),
('里', 'lǐ', 'داخل', 'beginner', 'basics'),
('上', 'shàng', 'فوق / أعلى', 'beginner', 'basics'),
('下', 'xià', 'تحت / أسفل', 'beginner', 'basics'),
('前', 'qián', 'أمام', 'beginner', 'basics'),
('后', 'hòu', 'خلف', 'beginner', 'basics'),
('左', 'zuǒ', 'يسار', 'beginner', 'basics'),
('右', 'yòu', 'يمين', 'beginner', 'basics'),
('住', 'zhù', 'يسكن', 'beginner', 'basics'),
('买', 'mǎi', 'يشتري', 'beginner', 'basics'),
('卖', 'mài', 'يبيع', 'beginner', 'basics'),
('钱', 'qián', 'نقود / مال', 'beginner', 'basics'),
('东西', 'dōng xi', 'شيء / أشياء', 'beginner', 'basics'),
('哪个', 'nǎ ge', 'أيّ واحد؟', 'beginner', 'basics'),
('这个', 'zhè ge', 'هذا الشيء', 'beginner', 'basics'),
('那个', 'nà ge', 'ذلك الشيء', 'beginner', 'basics'),
('回', 'huí', 'يرجع', 'beginner', 'basics'),
('开', 'kāi', 'يفتح', 'beginner', 'basics'),
('关', 'guān', 'يغلق', 'beginner', 'basics'),
('坐', 'zuò', 'يجلس', 'beginner', 'basics'),
('站', 'zhàn', 'يقف', 'beginner', 'basics'),
('走', 'zǒu', 'يمشي', 'beginner', 'basics'),
('跑', 'pǎo', 'يركض', 'beginner', 'basics'),
('睡觉', 'shuì jiào', 'ينام', 'beginner', 'basics'),
('起床', 'qǐ chuáng', 'يستيقظ', 'beginner', 'basics'),
('穿', 'chuān', 'يلبس', 'beginner', 'basics'),
('用', 'yòng', 'يستخدم', 'beginner', 'basics'),
('找', 'zhǎo', 'يبحث عن', 'beginner', 'basics'),
('等', 'děng', 'ينتظر', 'beginner', 'basics'),
('玩', 'wán', 'يلعب', 'beginner', 'basics'),
('打', 'dǎ', 'يضرب / يتصل', 'beginner', 'basics'),
('电话', 'diàn huà', 'هاتف', 'beginner', 'basics'),
('家', 'jiā', 'بيت / منزل', 'beginner', 'basics'),
('送', 'sòng', 'يرسل / يهدي', 'beginner', 'basics'),
('拿', 'ná', 'يأخذ / يحمل', 'beginner', 'basics'),
('放', 'fàng', 'يضع', 'beginner', 'basics'),
('笑', 'xiào', 'يضحك / يبتسم', 'beginner', 'basics'),
('哭', 'kū', 'يبكي', 'beginner', 'basics'),
('帮', 'bāng', 'يساعد', 'beginner', 'basics'),
('问', 'wèn', 'يسأل', 'beginner', 'basics'),
('答', 'dá', 'يجيب', 'beginner', 'basics'),
('教', 'jiāo', 'يعلّم', 'beginner', 'basics'),
('学', 'xué', 'يتعلم', 'beginner', 'basics'),
('忙', 'máng', 'مشغول', 'beginner', 'basics'),
('累', 'lèi', 'متعب', 'beginner', 'basics');

-- =====================================================
-- INTERMEDIATE LEVEL (~170 new words)
-- =====================================================

-- SCHOOL (intermediate) — additional school/education vocabulary
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('教室', 'jiào shì', 'فصل دراسي', 'intermediate', 'school'),
('课', 'kè', 'درس / حصة', 'intermediate', 'school'),
('课本', 'kè běn', 'كتاب مدرسي', 'intermediate', 'school'),
('黑板', 'hēi bǎn', 'سبورة', 'intermediate', 'school'),
('图书馆', 'tú shū guǎn', 'مكتبة', 'intermediate', 'school'),
('数学', 'shù xué', 'رياضيات', 'intermediate', 'school'),
('历史', 'lì shǐ', 'تاريخ', 'intermediate', 'school'),
('科学', 'kē xué', 'علوم', 'intermediate', 'school'),
('英语', 'yīng yǔ', 'اللغة الإنجليزية', 'intermediate', 'school'),
('大学', 'dà xué', 'جامعة', 'intermediate', 'school'),
('成绩', 'chéng jì', 'درجات / نتائج', 'intermediate', 'school'),
('毕业', 'bì yè', 'تخرّج', 'intermediate', 'school'),
('练习', 'liàn xí', 'تمرين / يتمرن', 'intermediate', 'school'),
('问题', 'wèn tí', 'سؤال / مشكلة', 'intermediate', 'school'),
('答案', 'dá àn', 'إجابة', 'intermediate', 'school'),
('铅笔', 'qiān bǐ', 'قلم رصاص', 'intermediate', 'school'),
('橡皮', 'xiàng pí', 'ممحاة', 'intermediate', 'school'),
('纸', 'zhǐ', 'ورق', 'intermediate', 'school'),
('字典', 'zì diǎn', 'قاموس', 'intermediate', 'school'),
('汉字', 'hàn zì', 'حرف صيني', 'intermediate', 'school');

-- FOOD (intermediate) — additional food vocabulary
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('肉', 'ròu', 'لحم', 'intermediate', 'food'),
('鸡肉', 'jī ròu', 'لحم دجاج', 'intermediate', 'food'),
('牛肉', 'niú ròu', 'لحم بقر', 'intermediate', 'food'),
('羊肉', 'yáng ròu', 'لحم غنم', 'intermediate', 'food'),
('鱼', 'yú', 'سمك', 'intermediate', 'food'),
('鸡蛋', 'jī dàn', 'بيض', 'intermediate', 'food'),
('米饭', 'mǐ fàn', 'أرز مطبوخ', 'intermediate', 'food'),
('面包', 'miàn bāo', 'خبز', 'intermediate', 'food'),
('蔬菜', 'shū cài', 'خضروات', 'intermediate', 'food'),
('牛奶', 'niú nǎi', 'حليب', 'intermediate', 'food'),
('咖啡', 'kā fēi', 'قهوة', 'intermediate', 'food'),
('果汁', 'guǒ zhī', 'عصير', 'intermediate', 'food'),
('糖', 'táng', 'سكر', 'intermediate', 'food'),
('盐', 'yán', 'ملح', 'intermediate', 'food'),
('饺子', 'jiǎo zi', 'زلابية صينية', 'intermediate', 'food'),
('包子', 'bāo zi', 'كعكة محشوة على البخار', 'intermediate', 'food'),
('苹果', 'píng guǒ', 'تفاحة', 'intermediate', 'food'),
('香蕉', 'xiāng jiāo', 'موز', 'intermediate', 'food'),
('西瓜', 'xī guā', 'بطيخ', 'intermediate', 'food'),
('蛋糕', 'dàn gāo', 'كعكة', 'intermediate', 'food'),
('饿', 'è', 'جائع', 'intermediate', 'food'),
('渴', 'kě', 'عطشان', 'intermediate', 'food'),
('好吃', 'hǎo chī', 'لذيذ', 'intermediate', 'food'),
('餐厅', 'cān tīng', 'مطعم', 'intermediate', 'food'),
('菜单', 'cài dān', 'قائمة الطعام', 'intermediate', 'food');

-- COLORS (intermediate) — additional colors
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('橙色', 'chéng sè', 'برتقالي', 'intermediate', 'colors'),
('紫色', 'zǐ sè', 'بنفسجي', 'intermediate', 'colors'),
('粉色', 'fěn sè', 'وردي', 'intermediate', 'colors'),
('灰色', 'huī sè', 'رمادي', 'intermediate', 'colors'),
('棕色', 'zōng sè', 'بني', 'intermediate', 'colors'),
('金色', 'jīn sè', 'ذهبي', 'intermediate', 'colors'),
('银色', 'yín sè', 'فضي', 'intermediate', 'colors'),
('深', 'shēn', 'غامق', 'intermediate', 'colors'),
('浅', 'qiǎn', 'فاتح', 'intermediate', 'colors'),
('颜色', 'yán sè', 'لون', 'intermediate', 'colors');

-- BODY (intermediate) — body parts
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('头', 'tóu', 'رأس', 'intermediate', 'body'),
('脸', 'liǎn', 'وجه', 'intermediate', 'body'),
('眼睛', 'yǎn jīng', 'عين', 'intermediate', 'body'),
('鼻子', 'bí zi', 'أنف', 'intermediate', 'body'),
('嘴', 'zuǐ', 'فم', 'intermediate', 'body'),
('耳朵', 'ěr duo', 'أذن', 'intermediate', 'body'),
('手', 'shǒu', 'يد', 'intermediate', 'body'),
('脚', 'jiǎo', 'قدم', 'intermediate', 'body'),
('腿', 'tuǐ', 'ساق', 'intermediate', 'body'),
('肚子', 'dù zi', 'بطن', 'intermediate', 'body'),
('背', 'bèi', 'ظهر', 'intermediate', 'body'),
('头发', 'tóu fa', 'شعر', 'intermediate', 'body'),
('牙齿', 'yá chǐ', 'أسنان', 'intermediate', 'body'),
('心', 'xīn', 'قلب', 'intermediate', 'body'),
('身体', 'shēn tǐ', 'جسم', 'intermediate', 'body');

-- ANIMALS (intermediate) — common animals
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('狗', 'gǒu', 'كلب', 'intermediate', 'animals'),
('猫', 'māo', 'قطة', 'intermediate', 'animals'),
('鸟', 'niǎo', 'طائر', 'intermediate', 'animals'),
('马', 'mǎ', 'حصان', 'intermediate', 'animals'),
('牛', 'niú', 'بقرة', 'intermediate', 'animals'),
('羊', 'yáng', 'خروف', 'intermediate', 'animals'),
('猪', 'zhū', 'خنزير', 'intermediate', 'animals'),
('鸡', 'jī', 'دجاجة', 'intermediate', 'animals'),
('鸭', 'yā', 'بطة', 'intermediate', 'animals'),
('兔子', 'tù zi', 'أرنب', 'intermediate', 'animals'),
('蛇', 'shé', 'ثعبان', 'intermediate', 'animals'),
('老虎', 'lǎo hǔ', 'نمر', 'intermediate', 'animals'),
('熊猫', 'xióng māo', 'باندا', 'intermediate', 'animals'),
('龙', 'lóng', 'تنين', 'intermediate', 'animals'),
('骆驼', 'luò tuo', 'جمل', 'intermediate', 'animals'),
('大象', 'dà xiàng', 'فيل', 'intermediate', 'animals'),
('猴子', 'hóu zi', 'قرد', 'intermediate', 'animals'),
('狮子', 'shī zi', 'أسد', 'intermediate', 'animals'),
('动物', 'dòng wù', 'حيوان', 'intermediate', 'animals'),
('宠物', 'chǒng wù', 'حيوان أليف', 'intermediate', 'animals');

-- WEATHER (intermediate)
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('天气', 'tiān qì', 'طقس', 'intermediate', 'weather'),
('晴天', 'qíng tiān', 'يوم مشمس', 'intermediate', 'weather'),
('阴天', 'yīn tiān', 'يوم غائم', 'intermediate', 'weather'),
('下雨', 'xià yǔ', 'تمطر', 'intermediate', 'weather'),
('下雪', 'xià xuě', 'تثلج', 'intermediate', 'weather'),
('风', 'fēng', 'رياح', 'intermediate', 'weather'),
('云', 'yún', 'سحاب', 'intermediate', 'weather'),
('太阳', 'tài yáng', 'شمس', 'intermediate', 'weather'),
('月亮', 'yuè liang', 'قمر', 'intermediate', 'weather'),
('星星', 'xīng xing', 'نجمة', 'intermediate', 'weather'),
('温度', 'wēn dù', 'درجة حرارة', 'intermediate', 'weather'),
('凉快', 'liáng kuai', 'منعش / بارد لطيف', 'intermediate', 'weather'),
('暖和', 'nuǎn huo', 'دافئ', 'intermediate', 'weather'),
('干', 'gān', 'جاف', 'intermediate', 'weather'),
('湿', 'shī', 'رطب', 'intermediate', 'weather');

-- TIME (intermediate) — additional time expressions
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('早上', 'zǎo shang', 'صباح', 'intermediate', 'time'),
('中午', 'zhōng wǔ', 'ظهر', 'intermediate', 'time'),
('下午', 'xià wǔ', 'بعد الظهر', 'intermediate', 'time'),
('晚上', 'wǎn shang', 'مساء', 'intermediate', 'time'),
('现在', 'xiàn zài', 'الآن', 'intermediate', 'time'),
('以前', 'yǐ qián', 'سابقاً / من قبل', 'intermediate', 'time'),
('以后', 'yǐ hòu', 'لاحقاً / بعد ذلك', 'intermediate', 'time'),
('小时', 'xiǎo shí', 'ساعة (وحدة زمنية)', 'intermediate', 'time'),
('分钟', 'fēn zhōng', 'دقيقة', 'intermediate', 'time'),
('星期', 'xīng qī', 'أسبوع', 'intermediate', 'time'),
('星期一', 'xīng qī yī', 'الإثنين', 'intermediate', 'time'),
('星期五', 'xīng qī wǔ', 'الجمعة', 'intermediate', 'time'),
('月', 'yuè', 'شهر', 'intermediate', 'time'),
('年', 'nián', 'سنة', 'intermediate', 'time'),
('每天', 'měi tiān', 'كل يوم', 'intermediate', 'time'),
('经常', 'jīng cháng', 'غالباً', 'intermediate', 'time'),
('有时候', 'yǒu shí hou', 'أحياناً', 'intermediate', 'time'),
('从来', 'cóng lái', 'أبداً / دائماً', 'intermediate', 'time'),
('已经', 'yǐ jīng', 'بالفعل / قد', 'intermediate', 'time'),
('刚才', 'gāng cái', 'للتو / قبل قليل', 'intermediate', 'time');

-- CLOTHING (intermediate)
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('衣服', 'yī fu', 'ملابس', 'intermediate', 'clothing'),
('裤子', 'kù zi', 'بنطلون', 'intermediate', 'clothing'),
('裙子', 'qún zi', 'تنورة', 'intermediate', 'clothing'),
('鞋子', 'xié zi', 'حذاء', 'intermediate', 'clothing'),
('帽子', 'mào zi', 'قبعة', 'intermediate', 'clothing'),
('外套', 'wài tào', 'معطف', 'intermediate', 'clothing'),
('衬衫', 'chèn shān', 'قميص', 'intermediate', 'clothing'),
('袜子', 'wà zi', 'جوارب', 'intermediate', 'clothing'),
('手套', 'shǒu tào', 'قفازات', 'intermediate', 'clothing'),
('围巾', 'wéi jīn', 'وشاح', 'intermediate', 'clothing');

-- TRANSPORT (intermediate)
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('车', 'chē', 'سيارة / مركبة', 'intermediate', 'transport'),
('公共汽车', 'gōng gòng qì chē', 'حافلة', 'intermediate', 'transport'),
('火车', 'huǒ chē', 'قطار', 'intermediate', 'transport'),
('飞机', 'fēi jī', 'طائرة', 'intermediate', 'transport'),
('地铁', 'dì tiě', 'مترو', 'intermediate', 'transport'),
('出租车', 'chū zū chē', 'سيارة أجرة', 'intermediate', 'transport'),
('自行车', 'zì xíng chē', 'دراجة', 'intermediate', 'transport'),
('船', 'chuán', 'سفينة / قارب', 'intermediate', 'transport'),
('机场', 'jī chǎng', 'مطار', 'intermediate', 'transport'),
('车站', 'chē zhàn', 'محطة', 'intermediate', 'transport'),
('路', 'lù', 'طريق', 'intermediate', 'transport'),
('开车', 'kāi chē', 'يقود سيارة', 'intermediate', 'transport'),
('停车', 'tíng chē', 'يوقف السيارة', 'intermediate', 'transport'),
('红绿灯', 'hóng lǜ dēng', 'إشارة مرور', 'intermediate', 'transport'),
('加油站', 'jiā yóu zhàn', 'محطة وقود', 'intermediate', 'transport');

-- PLACES (intermediate) — common locations
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('城市', 'chéng shì', 'مدينة', 'intermediate', 'transport'),
('邮局', 'yóu jú', 'مكتب بريد', 'intermediate', 'transport'),
('公园', 'gōng yuán', 'حديقة عامة', 'intermediate', 'transport'),
('电影院', 'diàn yǐng yuàn', 'سينما', 'intermediate', 'transport'),
('博物馆', 'bó wù guǎn', 'متحف', 'intermediate', 'transport'),
('药店', 'yào diàn', 'صيدلية', 'intermediate', 'transport'),
('警察局', 'jǐng chá jú', 'مركز شرطة', 'intermediate', 'transport');

-- ADDITIONAL FOOD (intermediate)
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('葡萄', 'pú tao', 'عنب', 'intermediate', 'food'),
('草莓', 'cǎo méi', 'فراولة', 'intermediate', 'food'),
('橙子', 'chéng zi', 'برتقال', 'intermediate', 'food'),
('番茄', 'fān qié', 'طماطم', 'intermediate', 'food'),
('土豆', 'tǔ dòu', 'بطاطس', 'intermediate', 'food'),
('豆腐', 'dòu fu', 'توفو', 'intermediate', 'food'),
('汤', 'tāng', 'حساء / شوربة', 'intermediate', 'food'),
('冰淇淋', 'bīng qí lín', 'آيس كريم', 'intermediate', 'food'),
('巧克力', 'qiǎo kè lì', 'شوكولاتة', 'intermediate', 'food'),
('辣', 'là', 'حار (توابل)', 'intermediate', 'food'),
('甜', 'tián', 'حلو', 'intermediate', 'food'),
('酸', 'suān', 'حامض', 'intermediate', 'food'),
('苦', 'kǔ', 'مرّ', 'intermediate', 'food');

-- =====================================================
-- ADVANCED LEVEL (~100 new words)
-- =====================================================

-- DAILY (advanced) — daily life & routines
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('生活', 'shēng huó', 'حياة', 'advanced', 'daily'),
('房子', 'fáng zi', 'منزل', 'advanced', 'daily'),
('房间', 'fáng jiān', 'غرفة', 'advanced', 'daily'),
('厨房', 'chú fáng', 'مطبخ', 'advanced', 'daily'),
('卫生间', 'wèi shēng jiān', 'حمام', 'advanced', 'daily'),
('客厅', 'kè tīng', 'غرفة المعيشة', 'advanced', 'daily'),
('洗', 'xǐ', 'يغسل', 'advanced', 'daily'),
('打扫', 'dǎ sǎo', 'ينظّف', 'advanced', 'daily'),
('做饭', 'zuò fàn', 'يطبخ', 'advanced', 'daily'),
('购物', 'gòu wù', 'يتسوّق', 'advanced', 'daily'),
('超市', 'chāo shì', 'سوبرماركت', 'advanced', 'daily'),
('商店', 'shāng diàn', 'متجر', 'advanced', 'daily'),
('银行', 'yín háng', 'بنك', 'advanced', 'daily'),
('医院', 'yī yuàn', 'مستشفى', 'advanced', 'daily'),
('医生', 'yī shēng', 'طبيب', 'advanced', 'daily'),
('药', 'yào', 'دواء', 'advanced', 'daily'),
('生病', 'shēng bìng', 'يمرض', 'advanced', 'daily'),
('健康', 'jiàn kāng', 'صحة / صحي', 'advanced', 'daily'),
('运动', 'yùn dòng', 'رياضة / يمارس الرياضة', 'advanced', 'daily'),
('锻炼', 'duàn liàn', 'يتمرّن', 'advanced', 'daily');

-- CONCEPTS (advanced) — abstract concepts & ideas
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('教育', 'jiào yù', 'تعليم', 'advanced', 'concepts'),
('知识', 'zhī shi', 'معرفة', 'advanced', 'concepts'),
('经验', 'jīng yàn', 'خبرة', 'advanced', 'concepts'),
('能力', 'néng lì', 'قدرة / مهارة', 'advanced', 'concepts'),
('责任', 'zé rèn', 'مسؤولية', 'advanced', 'concepts'),
('自由', 'zì yóu', 'حرية', 'advanced', 'concepts'),
('和平', 'hé píng', 'سلام', 'advanced', 'concepts'),
('发展', 'fā zhǎn', 'تطوير / تنمية', 'advanced', 'concepts'),
('进步', 'jìn bù', 'تقدّم', 'advanced', 'concepts'),
('计划', 'jì huà', 'خطة / يخطط', 'advanced', 'concepts'),
('目标', 'mù biāo', 'هدف', 'advanced', 'concepts'),
('方法', 'fāng fǎ', 'طريقة / أسلوب', 'advanced', 'concepts'),
('意见', 'yì jiàn', 'رأي', 'advanced', 'concepts'),
('决定', 'jué dìng', 'يقرر / قرار', 'advanced', 'concepts'),
('影响', 'yǐng xiǎng', 'تأثير / يؤثر', 'advanced', 'concepts'),
('关系', 'guān xì', 'علاقة', 'advanced', 'concepts'),
('社会', 'shè huì', 'مجتمع', 'advanced', 'concepts'),
('道德', 'dào dé', 'أخلاق', 'advanced', 'concepts'),
('传统', 'chuán tǒng', 'تقليد / تقليدي', 'advanced', 'concepts'),
('信任', 'xìn rèn', 'ثقة', 'advanced', 'concepts');

-- BUSINESS (advanced) — work & business
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('公司', 'gōng sī', 'شركة', 'advanced', 'business'),
('办公室', 'bàn gōng shì', 'مكتب', 'advanced', 'business'),
('经理', 'jīng lǐ', 'مدير', 'advanced', 'business'),
('员工', 'yuán gōng', 'موظف', 'advanced', 'business'),
('会议', 'huì yì', 'اجتماع', 'advanced', 'business'),
('合同', 'hé tong', 'عقد', 'advanced', 'business'),
('工资', 'gōng zī', 'راتب', 'advanced', 'business'),
('客户', 'kè hù', 'عميل / زبون', 'advanced', 'business'),
('市场', 'shì chǎng', 'سوق', 'advanced', 'business'),
('价格', 'jià gé', 'سعر', 'advanced', 'business'),
('贸易', 'mào yì', 'تجارة', 'advanced', 'business'),
('投资', 'tóu zī', 'استثمار', 'advanced', 'business'),
('经济', 'jīng jì', 'اقتصاد', 'advanced', 'business'),
('广告', 'guǎng gào', 'إعلان', 'advanced', 'business'),
('品牌', 'pǐn pái', 'علامة تجارية', 'advanced', 'business');

-- TECHNOLOGY (advanced)
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('手机', 'shǒu jī', 'هاتف محمول', 'advanced', 'technology'),
('网络', 'wǎng luò', 'شبكة / إنترنت', 'advanced', 'technology'),
('网站', 'wǎng zhàn', 'موقع إلكتروني', 'advanced', 'technology'),
('软件', 'ruǎn jiàn', 'برنامج / برمجيات', 'advanced', 'technology'),
('应用', 'yìng yòng', 'تطبيق', 'advanced', 'technology'),
('数据', 'shù jù', 'بيانات', 'advanced', 'technology'),
('密码', 'mì mǎ', 'كلمة مرور', 'advanced', 'technology'),
('下载', 'xià zài', 'يحمّل (تنزيل)', 'advanced', 'technology'),
('上传', 'shàng chuán', 'يرفع (رفع ملفات)', 'advanced', 'technology'),
('搜索', 'sōu suǒ', 'يبحث (على الإنترنت)', 'advanced', 'technology'),
('信息', 'xìn xī', 'معلومات / رسالة', 'advanced', 'technology'),
('人工智能', 'rén gōng zhì néng', 'ذكاء اصطناعي', 'advanced', 'technology'),
('科技', 'kē jì', 'تكنولوجيا', 'advanced', 'technology'),
('程序', 'chéng xù', 'برنامج (كود)', 'advanced', 'technology'),
('屏幕', 'píng mù', 'شاشة', 'advanced', 'technology');

-- TRAVEL (advanced)
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('旅行', 'lǚ xíng', 'سفر / رحلة', 'advanced', 'travel'),
('护照', 'hù zhào', 'جواز سفر', 'advanced', 'travel'),
('签证', 'qiān zhèng', 'تأشيرة', 'advanced', 'travel'),
('酒店', 'jiǔ diàn', 'فندق', 'advanced', 'travel'),
('行李', 'xíng li', 'أمتعة', 'advanced', 'travel'),
('地图', 'dì tú', 'خريطة', 'advanced', 'travel'),
('景点', 'jǐng diǎn', 'معلم سياحي', 'advanced', 'travel'),
('导游', 'dǎo yóu', 'مرشد سياحي', 'advanced', 'travel'),
('预订', 'yù dìng', 'يحجز', 'advanced', 'travel'),
('国际', 'guó jì', 'دولي', 'advanced', 'travel'),
('外国', 'wài guó', 'بلد أجنبي', 'advanced', 'travel'),
('迪拜', 'dí bài', 'دبي', 'advanced', 'travel'),
('阿联酋', 'ā lián qiú', 'الإمارات العربية المتحدة', 'advanced', 'travel'),
('北京', 'běi jīng', 'بكين', 'advanced', 'travel'),
('上海', 'shàng hǎi', 'شنغهاي', 'advanced', 'travel');

-- EMOTIONS (advanced)
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('高兴', 'gāo xìng', 'سعيد / مسرور', 'advanced', 'emotions'),
('难过', 'nán guò', 'حزين', 'advanced', 'emotions'),
('生气', 'shēng qì', 'غاضب', 'advanced', 'emotions'),
('害怕', 'hài pà', 'خائف', 'advanced', 'emotions'),
('紧张', 'jǐn zhāng', 'متوتر', 'advanced', 'emotions'),
('着急', 'zháo jí', 'قلق / مستعجل', 'advanced', 'emotions'),
('无聊', 'wú liáo', 'يشعر بالملل', 'advanced', 'emotions'),
('感动', 'gǎn dòng', 'متأثر / مؤثر', 'advanced', 'emotions'),
('骄傲', 'jiāo ào', 'فخور', 'advanced', 'emotions'),
('满意', 'mǎn yì', 'راضٍ', 'advanced', 'emotions'),
('失望', 'shī wàng', 'محبط / خائب الأمل', 'advanced', 'emotions'),
('惊讶', 'jīng yà', 'مندهش', 'advanced', 'emotions'),
('感觉', 'gǎn jué', 'يشعر / إحساس', 'advanced', 'emotions'),
('心情', 'xīn qíng', 'مزاج', 'advanced', 'emotions'),
('放松', 'fàng sōng', 'يسترخي', 'advanced', 'emotions');

-- NATURE (advanced)
INSERT INTO vocab (hanzi, pinyin, arabic_translation, level, category) VALUES
('山', 'shān', 'جبل', 'advanced', 'nature'),
('河', 'hé', 'نهر', 'advanced', 'nature'),
('海', 'hǎi', 'بحر', 'advanced', 'nature'),
('湖', 'hú', 'بحيرة', 'advanced', 'nature'),
('树', 'shù', 'شجرة', 'advanced', 'nature'),
('花', 'huā', 'زهرة', 'advanced', 'nature'),
('草', 'cǎo', 'عشب', 'advanced', 'nature'),
('天空', 'tiān kōng', 'سماء', 'advanced', 'nature'),
('地球', 'dì qiú', 'الأرض (كوكب)', 'advanced', 'nature'),
('沙漠', 'shā mò', 'صحراء', 'advanced', 'nature'),
('森林', 'sēn lín', 'غابة', 'advanced', 'nature'),
('环境', 'huán jìng', 'بيئة', 'advanced', 'nature'),
('污染', 'wū rǎn', 'تلوث', 'advanced', 'nature'),
('保护', 'bǎo hù', 'يحمي / حماية', 'advanced', 'nature'),
('空气', 'kōng qì', 'هواء', 'advanced', 'nature');
